### ISSUE TITLE
Iterate over possible ci.yml filenames when trigger CI run from gha-merge-up

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/gha-merge-up#14]
Now that github actions have their own ci actions we need to the logic to run ci.yml via github-api in gha-merge-up

https://github.com/silverstripe/gha-merge-up/blob/1.0/action.yml

The CI files can be called one of the following:

action-ci-self.yml | action-ci.yml | ci.yml

Iterate of these filenames in this particular order and run the first one that matches

## PRs
- https://github.com/silverstripe/gha-merge-up/pull/15

**Comment by GuySartorelli** [comment]
PR merged
