### ISSUE TITLE
gha repositories are still failing to parse __composer.json

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/gha-merge-up#22]
Check that __composer.json exists on the repositories before trying to download it, otherwise you'll still end up with a __composer.json file just it will be blank or an error, though still passed the php file_exists() check

## PRs
- https://github.com/silverstripe/gha-merge-up/pull/23

**Comment by GuySartorelli** [comment]
PR merged. Reassigning to @emteknetnz to see if this actually fixed the problem - as mentioned in https://github.com/silverstripe/gha-merge-up/pull/23#pullrequestreview-1597482240 there's not enough information here for me to make that determination.

**Comment by emteknetnz** [comment]
Works now https://github.com/silverstripe/gha-ci/actions/runs/5996153545/job/16260227717
