### ISSUE TITLE
Doesn't know how to merge up new repositories

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/gha-merge-up#28]
Failed merge-up in https://github.com/silverstripe/markdown-php-codesniffer/actions/runs/6973288579/job/18977009246 is due to faulty or missing logic in this action:

> PHP Fatal error:  Uncaught Exception: Could not work out what the default CMS major version this module uses in /home/runner/work/_actions/silverstripe/gha-merge-up/v1/funcs.php:87
Stack trace:
`#0` /home/runner/work/_actions/silverstripe/gha-merge-up/v1/branches.php(9): branches()
`#1` {main}
  thrown in /home/runner/work/_actions/silverstripe/gha-merge-up/v1/funcs.php on line 87

## Acceptance criteria
- The merge-up action in silverstripe/markdown-php-codesniffer works without errors
- All new repositories will work without needing a change each time one is added
  OR
- The instructions for [setting up a new repository](https://silverstripe.atlassian.net/wiki/spaces/CMS/pages/3030679981/Setting+up+a+new+GitHub+repository) include whatever steps are necessary to get merge-ups working.

## PRs
- https://github.com/silverstripe/markdown-php-codesniffer/pull/4
- https://github.com/silverstripe/gha-merge-up/pull/29

**Comment by GuySartorelli** [comment]
@emteknetnz The fragility of merge-ups requiring a specific minimum PHP version should be documented, either in the merge-ups readme or the "adding a new repo" page.

**Comment by emteknetnz** [comment]
Done

**Comment by GuySartorelli** [comment]
Merged
