### ISSUE TITLE
gha-merge-up - Merge-up javascript

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/gha-merge-up#3]
Follow up issue from https://github.com/silverstripeltd/product-issues/issues/753

[gha-merge-up](https://github.com/silverstripe/gha-merge-up/) currently does not support js files, instead it will fail any build that includes `client/` in the files diff

### ACs
- [ ] Diffs that include `client/` filter are allowed
- [ ] If changes in the `client/` are detected, for non silverstripe/admin modules, silverstripe/admin is installed in a sibling directory and yarn install is run (see [gha-update-js](https://github.com/silverstripe/gha-update-js/) for how to do this)
- [ ] `nvm use <correct_version>` is run where `correct_version` is correct for the major version being merged-into
- [ ] `yarn build` is run in the module being merged-up
- [ ] The build fails if there is any issue with `yarn build`
- [ ] Any updated dist files are git added
- [ ] Initially, only asset-admin will use this functionality

### Follow up issues created
- https://github.com/silverstripe/gha-generate-matrix/issues/59

### PRs
- https://github.com/silverstripe/gha-merge-up/pull/6
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1375

**Comment by GuySartorelli** [comment]
PRs merged, all ACs met.
