### ISSUE TITLE
gha-merge-up not always merging up

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/gha-merge-up#39]
## Problem 1 - not merging up when there are actual changes to files

With some modules (possibly all but I have only seen it on a couple), the merge-up isn't performed when there are changes only to workflow files. There may be other cases as well where the merge-up doesn't happen as expected.

https://github.com/symbiote/silverstripe-multivaluefield/compare/6...6.1
![image](https://github.com/silverstripe/gha-merge-up/assets/36352093/5836ffc0-5955-4e9c-baba-b9e640296752)
[The mergeup job](https://github.com/symbiote/silverstripe-multivaluefield/actions/runs/9215817570/job/25354893303) says
>  No changes found when merging-up 6.1 into 6. Skipping.

## Problem 2 - not merging up when there are commits but no file changes to merge

Rhino shows branches as needing to be merged up based on _commits_, not based on changes to files. e.g. in these screenshots the `1.13` branch needs to be merged up to the `1` branch, but we can see no changes to actual files.
![image](https://github.com/silverstripe/gha-merge-up/assets/36352093/ea022af2-e738-48b9-8234-282c8c634d48)
![image](https://github.com/silverstripe/gha-merge-up/assets/36352093/55e18368-bbd9-47a2-85a3-f1fae7f7a6f3)

For best results, the merge-up action should always perform a merge when there are commits in one branch that aren't in another branch, even when there is no actual change to files. This will remove edge cases, line up with what Rhino reports, and would automatically resolve problem 1 above as well.

## Acceptance criteria
- gha-merge-up always makes a merge commit when one branch has commits that don't exist in another branch, regardless of whether there are changes to files
  - All the existing protections e.g. not merging for composer.json changes etc still apply

## PR
- https://github.com/silverstripe/gha-merge-up/pull/40

**Comment by emteknetnz** [comment]
I can't replicate Problem 1

What I tried:
1. forked symbiote/silverstripe-multivaluefield to my emteknetnz account
1. Deleted the 6.1 branch
1. Created the 6.1 branch from the 6 branch
1. Changed a workflow file (ci.yml) on the 6.1 branch
1. Ran the Merge-up workflow on the default 5 branch

```
Automatic merge went well; stopped before committing as requested
[6 b174234] Merge branch '6.1' into 6
To https://github.com/emteknetnz/silverstripe-multivaluefield
   a29bc37..b174234  6 -> 6
Succesfully merged-up 6.1 into 6
```

The 6 branch now has the change on it https://github.com/emteknetnz/silverstripe-multivaluefield/blob/6/.github/workflows/ci.yml#L13

**Comment by emteknetnz** [comment]
Have created PR, linked in description. As mentioned in description, hopefully solving problem 2 fixes problem 1

**Comment by GuySartorelli** [comment]
PR merged. Reassigning to Steve to rerun the mergeups that rhino says are needed (or to leave it open and let it run naturally, or to close)

**Comment by emteknetnz** [comment]
Will just close
