### ISSUE TITLE
Cannot rebuild JS on CMS 6 branches

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/gha-merge-up#46]
https://github.com/silverstripe/silverstripe-elemental/actions/runs/12248835267/job/34169150272

   Problem 1
    - Root composer.json requires dnadesign/silverstripe-elemental 6.x-dev -> satisfiable by dnadesign/silverstripe-elemental[6.x-dev].
    - dnadesign/silverstripe-elemental 6.x-dev requires php ^8.3 -> your php version (8.1.31) does not satisfy that requirement.

## PR
- https://github.com/silverstripe/gha-merge-up/pull/47

**Comment by GuySartorelli** [comment]
PR merged. Reassigning to Steve to check if this fixed the problem.

**Comment by emteknetnz** [comment]
It did https://github.com/silverstripe/silverstripe-linkfield/pull/355
